products = [
  {
    "_id": "1",
    "name": "Freshly Brewed Coffee",
    "image": "/images/freshlybrewedcoffee.jpg",
    "description":
      "A coffee to deal with a stressful day ahead and a stressfaul day gone.",
    "item": "Coffee",
    "category": "Hot",
    "price": 3.99,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "2",
    "name": "Espresso",
    "image": "/images/espresso.jpg",
    "description": "A coffee for the adventurous who want to feel the kick.",
    "item": "Coffee",
    "category": "Hot",
    "price": 4.99,
    "countInStock": 7,
    "rating": 4.0,
    "numReviews": 8,
  },
  {
    "_id": "3",
    "name": "Kaapi Latte",
    "image": "/images/latte.jpg",
    "description":
      "A latte made with the fresh beans brewed by Kaapi Shop, and topped by flavours of your choice",
    "item": "Coffee",
    "category": "Hot",
    
    "price": 4.99,
    "countInStock": 7,
    "rating": 4.6,
    "numReviews": 10,
  },
  {
    "_id": "4",
    "name": "Iced Coffee",
    "image": "/images/icedcoffee.jpg",
    "description":
      "The ultimate iced coffee, with additional flavours of your choice.",
    "item": "Coffee",
    "category": "Cold",
    "price": 4.99,
    "countInStock": 11,
    "rating": 5,
    "numReviews": 12,
  },
  {
    "_id": "5",
    "name": "Elite Veggie Sandwich",
    "image": "/images/sandwich.jpg",
    "description": "A tasteful treat for the tastebuds",
    "item": "Sandwich",
    "category": "veg",
    "price": 5.99,
    "countInStock": 5,
    "rating": 4.8,
    "numReviews": 12,
  },
  {
    "_id": "6",
    "name": "Cheese Burger",
    "image": "/images/burger.jpg",
    "description": "A treat for the body, mind and the soul.",
    "item": "Burgers",
    "category": "nonveg",
    "price": 9.99,
    "countInStock": 0,
    "rating": 4.9,
    "numReviews": 12,
  },
];

